;[
  {
    id: 1,
    title: 'Мужские Кроссовки Nike Blazer Mid Suede',
    price: 12999,
    imageUrl: [
      '/sneakers/sneakers-1/sneakers-1-1.png',
      '/sneakers/sneakers-1/sneakers-1-2.png',
      '/sneakers/sneakers-1/sneakers-1-3.png',
      '/sneakers/sneakers-1/sneakers-1-4.png',
      '/sneakers/sneakers-1/sneakers-1-5.png',
      '/sneakers/sneakers-1/sneakers-1-6.png',
    ],
    description: 'sfdfsdf',
  },
  {
    id: 2,
    title: 'Мужские Кроссовки Reebok ZIGNITION',
    price: 15600,
    imageUrl: [
      '/sneakers/Reebok ZIGNITION/Reebok ZIGNITION-1.png',
      '/sneakers/Reebok ZIGNITION/Reebok ZIGNITION-2.png',
      '/sneakers/Reebok ZIGNITION/Reebok ZIGNITION-3.png',
      '/sneakers/Reebok ZIGNITION/Reebok ZIGNITION-4.png',
      '/sneakers/Reebok ZIGNITION/Reebok ZIGNITION-5.png',
      '/sneakers/Reebok ZIGNITION/Reebok ZIGNITION-6.png',
    ],
    description: 'sfdfsdf',
  },
  {
    id: 3,
    title: 'Мужские Кроссовки Reebok ZIG KINETICA',
    price: 8499,
    imageUrl: [
      '/sneakers/Reebok ZIG KINETICA 2.5 EDGE WINTER/Reebok ZIG KINETICA 2.5 EDGE WINTER-1.png',
      '/sneakers/Reebok ZIG KINETICA 2.5 EDGE WINTER/Reebok ZIG KINETICA 2.5 EDGE WINTER-2.png',
      '/sneakers/Reebok ZIG KINETICA 2.5 EDGE WINTER/Reebok ZIG KINETICA 2.5 EDGE WINTER-3.png',
      '/sneakers/Reebok ZIG KINETICA 2.5 EDGE WINTER/Reebok ZIG KINETICA 2.5 EDGE WINTER-4.png',
      '/sneakers/Reebok ZIG KINETICA 2.5 EDGE WINTER/Reebok ZIG KINETICA 2.5 EDGE WINTER-5.png',
      '/sneakers/Reebok ZIG KINETICA 2.5 EDGE WINTER/Reebok ZIG KINETICA 2.5 EDGE WINTER-6.png',
    ],
    description: 'sfdfsdf',
  },
  {
    id: 4,
    title: 'Кроссовки Reebok VERSE',
    price: 7800,
    imageUrl: [
      '/sneakers/Reebok VERSE/Reebok VERSE-1.png',
      '/sneakers/Reebok VERSE/Reebok VERSE-2.png',
      '/sneakers/Reebok VERSE/Reebok VERSE-3.png',
      '/sneakers/Reebok VERSE/Reebok VERSE-4.png',
      '/sneakers/Reebok VERSE/Reebok VERSE-5.png',
      '/sneakers/Reebok VERSE/Reebok VERSE-6.png',
    ],
    description: 'sfdfsdf',
  },
  {
    id: 5,
    title: 'Кроссовки Reebok SMASH EDGE',
    price: 9550,
    imageUrl: [
      '/sneakers/Reebok SMASH EDGE/Reebok SMASH EDGE-1.png',
      '/sneakers/Reebok SMASH EDGE/Reebok SMASH EDGE-2.png',
      '/sneakers/Reebok SMASH EDGE/Reebok SMASH EDGE-3.png',
      '/sneakers/Reebok SMASH EDGE/Reebok SMASH EDGE-4.png',
      '/sneakers/Reebok SMASH EDGE/Reebok SMASH EDGE-5.png',
      '/sneakers/Reebok SMASH EDGE/Reebok SMASH EDGE-6.png',
    ],
    description: 'sfdfsdf',
  },
  {
    id: 6,
    title: 'Кроссовки Reebok Nano X5',
    price: 16999,
    imageUrl: [
      '/sneakers/Reebok Nano X5 Edge/Reebok Nano X5 Edge-1.png',
      '/sneakers/Reebok Nano X5 Edge/Reebok Nano X5 Edge-2.png',
      '/sneakers/Reebok Nano X5 Edge/Reebok Nano X5 Edge-3.png',
      '/sneakers/Reebok Nano X5 Edge/Reebok Nano X5 Edge-4.png',
      '/sneakers/Reebok Nano X5 Edge/Reebok Nano X5 Edge-5.png',
      '/sneakers/Reebok Nano X5 Edge/Reebok Nano X5 Edge-6.png',
    ],
    description: 'sfdfsdf',
  },
  {
    id: 7,
    title: 'Кроссовки Reebok MUNDO',
    price: 7499,
    imageUrl: [
      '/sneakers/Reebok MUNDO/Reebok MUNDO-1.png',
      '/sneakers/Reebok MUNDO/Reebok MUNDO-2.png',
      '/sneakers/Reebok MUNDO/Reebok MUNDO-3.png',
      '/sneakers/Reebok MUNDO/Reebok MUNDO-4.png',
      '/sneakers/Reebok MUNDO/Reebok MUNDO-5.png',
      '/sneakers/Reebok MUNDO/Reebok MUNDO-6.png',
    ],
    description: 'sfdfsdf',
  },
  {
    id: 8,
    title: 'Кроссовки Reebok EDGEWOOD',
    price: 15600,
    imageUrl: [
      '/sneakers/Reebok EDGEWOOD/Reebok EDGEWOOD-1.png',
      '/sneakers/Reebok EDGEWOOD/Reebok EDGEWOOD-2.png',
      '/sneakers/Reebok EDGEWOOD/Reebok EDGEWOOD-3.png',
      '/sneakers/Reebok EDGEWOOD/Reebok EDGEWOOD-4.png',
      '/sneakers/Reebok EDGEWOOD/Reebok EDGEWOOD-5.png',
      '/sneakers/Reebok EDGEWOOD/Reebok EDGEWOOD-6.png',
    ],
    description: 'sfdfsdf',
  },
  {
    id: 9,
    title: 'Кроссовки PUMA SOFTRIDE COSMIC LT',
    price: 5900,
    imageUrl: [
      '/sneakers/PUMA SOFTRIDE COSMIC LT/PUMA SOFTRIDE COSMIC LT-1.png',
      '/sneakers/PUMA SOFTRIDE COSMIC LT/PUMA SOFTRIDE COSMIC LT-2.png',
      '/sneakers/PUMA SOFTRIDE COSMIC LT/PUMA SOFTRIDE COSMIC LT-3.png',
      '/sneakers/PUMA SOFTRIDE COSMIC LT/PUMA SOFTRIDE COSMIC LT-4.png',
      '/sneakers/PUMA SOFTRIDE COSMIC LT/PUMA SOFTRIDE COSMIC LT-5.png',
      '/sneakers/PUMA SOFTRIDE COSMIC LT/PUMA SOFTRIDE COSMIC LT-6.png',
    ],
    description: 'sfdfsdf',
  },
  {
    id: 10,
    title: 'Кроссовки PUMA SOFTRIDE',
    price: 11500,
    imageUrl: [
      '/sneakers/PUMA SOFTRIDE/PUMA SOFTRIDE-1.png',
      '/sneakers/PUMA SOFTRIDE/PUMA SOFTRIDE-2.png',
      '/sneakers/PUMA SOFTRIDE/PUMA SOFTRIDE-3.png',
      '/sneakers/PUMA SOFTRIDE/PUMA SOFTRIDE-4.png',
      '/sneakers/PUMA SOFTRIDE/PUMA SOFTRIDE-5.png',
      '/sneakers/PUMA SOFTRIDE/PUMA SOFTRIDE-6.png',
    ],
    description: 'sfdfsdf',
  },
  {
    id: 11,
    title: 'Кроссовки PUMA COURT PRO 2',
    price: 7600,
    imageUrl: [
      '/sneakers/PUMA COURT PRO 2/PUMA COURT PRO 2-1.png',
      '/sneakers/PUMA COURT PRO 2/PUMA COURT PRO 2-2.png',
      '/sneakers/PUMA COURT PRO 2/PUMA COURT PRO 2-3.png',
      '/sneakers/PUMA COURT PRO 2/PUMA COURT PRO 2-4.png',
      '/sneakers/PUMA COURT PRO 2/PUMA COURT PRO 2-5.png',
      '/sneakers/PUMA COURT PRO 2/PUMA COURT PRO 2-6.png',
    ],
    description: 'sfdfsdf',
  },
  {
    id: 12,
    title: 'Кроссовки Nike Defyallday',
    price: 13000,
    imageUrl: [
      '/sneakers/Nike Defyallday/Nike Defyallday-1.png',
      '/sneakers/Nike Defyallday/Nike Defyallday-2.png',
      '/sneakers/Nike Defyallday/Nike Defyallday-3.png',
      '/sneakers/Nike Defyallday/Nike Defyallday-4.png',
      '/sneakers/Nike Defyallday/Nike Defyallday-5.png',
      '/sneakers/Nike Defyallday/Nike Defyallday-6.png',
    ],
    description: 'sfdfsdf',
  },
]
